In [2]:
import numpy as np
import random
def pad_with(vector, pad_width, iaxis, kwargs):
  pad_value = kwargs.get('padder', 10)
  vector[:pad_width[0]] = pad_value
  vector[-pad_width[1]:] = pad_value
def create_field(w=6, h=9, num_opp=5):
  HEIGHT = h
  WIDTH  = w
  NumOpp = num_opp
  field = np.zeros((HEIGHT, WIDTH))
  # 1:ball, 2:basket, 1.new_ball_pos(tmp) 3:opponents, 4:agent 5:outside

  # create ball
  ball_pos = np.array([HEIGHT//2, 0])
  # field[HEIGHT//2][0] = 1

  # create basket
  basket_pos = np.array([HEIGHT//2, WIDTH-1])
  field[HEIGHT//2][WIDTH-1] = 2

  # mark new_ball_pos
  field[HEIGHT//2][round(WIDTH*0.8)] = 1

  opp_pos = [] 
  # create the opponents
  x = random.randint(0, HEIGHT-1)
  y = random.randint(0, WIDTH-1)
  # prevent opponent in the cell of balls
  for i in range(NumOpp): 
    while field[x][y] != 0:
      x = random.randint(0, HEIGHT-1)
      y = random.randint(0, WIDTH-1)
    field[x][y] = 3
    opp_pos.append(np.array([x, y]))
  
  # de-mark new_ball_pos
  field[HEIGHT//2][round(WIDTH*0.8)] = 0

  # in order the boundary condition
  return field, basket_pos, ball_pos, opp_pos 
def create_agent(field):
  h, w = field.shape
  x = random.randint(0, HEIGHT-1)
  y = random.randint(0, WIDTH-1)
  while field[x][y] != 0:
    x = random.randint(0, HEIGHT-1)
    y = random.randint(0, WIDTH-1)
  # field[x][y] = 4
  agent_pos = np.array([x, y])
  return field, agent_pos

In [3]:
HEIGHT= 12
WIDTH = 15
NUM_OPP = 50
field, basket_pos, ball_pos, opp_pos = create_field(w=WIDTH,h=HEIGHT,num_opp=NUM_OPP)
field, agent_pos = create_agent(field)
print('field')
print(field)
print(f'basket: {basket_pos}')
print(f'{ball_pos}')
print(f'opponent:{opp_pos}')
print(f'agent:{agent_pos}')

field
[[0. 3. 0. 3. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0.]
 [3. 3. 0. 3. 0. 3. 3. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 3. 0. 3. 3. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3.]
 [0. 0. 0. 3. 3. 0. 0. 0. 0. 3. 3. 0. 0. 0. 0.]
 [0. 3. 3. 0. 0. 3. 0. 0. 0. 0. 0. 3. 0. 3. 3.]
 [0. 3. 0. 3. 0. 0. 0. 3. 0. 0. 0. 3. 0. 3. 2.]
 [3. 0. 0. 3. 0. 0. 0. 0. 3. 0. 3. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0. 3. 0. 3. 3. 3. 0. 3.]
 [0. 3. 0. 0. 0. 3. 3. 3. 0. 3. 0. 0. 0. 0. 3.]
 [0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 3. 0. 0. 3. 0. 3. 3.]]
basket: [ 6 14]
[6 0]
opponent:[array([5, 2]), array([ 9, 14]), array([9, 9]), array([9, 6]), array([0, 1]), array([9, 7]), array([1, 1]), array([ 8, 14]), array([1, 3]), array([1, 6]), array([2, 1]), array([0, 7]), array([1, 0]), array([11,  8]), array([7, 8]), array([11, 14]), array([ 6, 13]), array([ 3, 14]), array([ 5, 13]), array([2, 3]), array([9, 1]), array([ 8, 10]), array([4, 4]), array([6, 1]), array([7,